### ISSUE TITLE
test spec on meals() method in Neighborhood class is too difficult

### ISSUE THREAD

**Issue by ICanDoAllThingThroughChrist** [learn-co-curriculum/js-looping-and-iteration-filter-lab#8] opened 2018-12-29 21:06 UTC
commenting final code from another classmate is the only method I could learn. 

the test spec below may work well for spec writer, but not for learning to code.
  describe('Neighborhood methods', () => {
      describe('meals()', () => {
        it('returns a unique list of meals orderd in a neighborhood', () => {
          expect(upperEast.meals().length).to.equal(3);
        });

**Comment by sgharms** [comment] 2019-01-02 18:42
@ICanDoAllThingThroughChrist Can you specify what's problematic for you here? Is it the description in the spec file? The arrow function syntax?

**Comment by sgharms** [comment] 2019-01-02 18:47
Also, I don't see that there's anything about meals() in the readme. I looked at your fork:

https://github.com/ICanDoAllThingThroughChrist/js-looping-and-iteration-filter-lab-v-000

and don't see any mention of `Neighborhood`. Is this issue on the right repo?

**Comment by sgharms** [comment] 2019-01-03 14:48
@ICanDoAllThingThroughChrist I'm going to close this pending your reply. Please re-open when you can update.

**Comment by ICanDoAllThingThroughChrist** [comment] 2019-01-04 13:44
Description test for meals () call is in indexTest.js.
 I still do not understand how one would arrive at the solution  based on the test alone.
  It is like filling the blank in a english composition test but with no prior reading of the solution or similar reference.
 Iteration in the dark. 

Rather i need a recipe book of doable codes that I can drill rather wasting precious time in the dark.

**Comment by sgharms** [comment] 2019-01-04 14:22
@ICanDoAllThingThroughChrist 

1. I cloned your fork of the repository: https://github.com/ICanDoAllThingThroughChrist/js-looping-and-iteration-filter-lab-v-000
2. I searched through all the files in it for the code you included:

```js
describe('Neighborhood methods', () => {
describe('meals()', () => {
it('returns a unique list of meals orderd in a neighborhood', () => {
expect(upperEast.meals().length).to.equal(3);
});
```

...and got nothing back...

```sh
➜  js-looping-and-iteration-filter-lab-v-000 git:(master) ack orderd
➜  js-looping-and-iteration-filter-lab-v-000 git:(master) ack upperEast
➜  js-looping-and-iteration-filter-lab-v-000 git:(master)
```

This leads me to believe that the difficulty is not in the `js-looping-and-iteration-filter-lab`, but in a different lab. Is that right? If so, can you please provide me the name of the lab from which this code sample came?

**Comment by ICanDoAllThingThroughChrist** [comment] 2019-01-04 17:00
Daily lunch lab is the 1

**Comment by sgharms** [comment] 2019-01-04 18:33
I think this, as well, should be handled through ask a question.

GitHub's issues are opened on a per-repository basis. If you need help opening issues on the lab where the problem is, please use the AAQ feature to get some coaching on it.

You seem to be expressing some frustration about how to solve a test. Here's how I think about it:
Look at the expectation.

`expect(upperEast.meals().length).to.equal(3)`

In the spec file there's a thing called `upperEast`. What is that? We define it for you (line 229). It's an instance of a `Neighborhood` class. Do you know how to add methods to the `Neighborhood` class? If not, AAQ; if so, move to the next step.

So `Neighborhood` needs an *instance*  method called `meals`. Do you know how to write those? If not, AAQ; if so, move on.

Can you make that method return a thing that will respond to `.length` with the number 3.

Think of it less like fill-in-the-blank and more like algebra. Algebra requires you to understand what's there in order to find out how to create a what's missing.

Good luck!

**Closed as completed by sgharms** 2019-01-04 18:33 UTC
Labels: Test
